version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "8080:15672"
      - "5672:5672"
    restart: always
    tty: true

  app:
    build: .
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
