version: "3.1"

services:
  sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/rabbitmqapp
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-tier

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    restart: always
    env_file:
      - ./un.env
    volumes:
      - .:/usr/rabbitmqapp
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-tier

  rabbitmq:
    tty: true
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 30s
        retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .:/usr/rabbitmqapp/queues
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge